name: data514
channels:
  - defaults
dependencies:
  - pip=22.3
  - python=3.10
  - jupyter=1
  - notebook=6
  - pandas=1.5
  - numpy-base=1.23.5
  - matplotlib
  - openjdk # This is for Java
  - pip:
      - numpy==1.24.1
      - ISLP
      - pymongo
      - pyspark # This is for PySpark
      - findspark # This helps to find Spark on your system
